name: Build and Deploy to Production
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build -- --configuration=test
      - name: Choose Firebase Project
        uses: w9jds/firebase-action@master
        with:
          args: use test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy angular app to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}